print("---------------------------------")
print("Hi, Good day!")
print("Welcome to ADDITION QUIZ!")
print("---------------------------------")
print("Please answer the questions below:")
print("---------------------------------")